piVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  selector:
    matchLabels:
      app: vproapp
  replicas: 1 
  template:
    metadata: 
      labels:
        app: vproapp 
    spec:
      
      initContainers:
        - name: init-db-waiter
          image: busybox
          command: ['sh', '-c', 'until nslookup vprodb; do echo "waiting for mydb"; sleep 2; done;']
          # waiting for the DB service to be up
        - name: init-memcache-waiter
          image: busybox
          command: ['sh', '-c', 'until nslookup vprocache01; do echo "waiting for mydb"; sleep 2; done;']   
          # waiting for the memcache service to be up

      containers:
        - name: vproapp-container
          image: {{ .Values.appimage}}
          ports:
            - name: vproapp-port
              containerPort: 8080

      imagePullSecrets:
        - regcred 


          
               